// this version created by the windows configure system
#ifdef _WIN32

/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Apr  5, 2018
 *			
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
	"        SUMMARY OF THE HDF5 CONFIGURATION\n"
	"        =================================\n"
	"\n"
	"General Information:\n"
	"-------------------\n"
	"                   HDF5 Version: 1.10.2\n"
	"                  Configured on: 2018-04-05\n"
	"                  Configured by: Visual Studio 14 2015 Win64\n"
	"                    Host system: Windows-10.0.16299\n"
	"              Uname information: Windows\n"
	"                       Byte sex: little-endian\n"
	"             Installation point: C:/Program Files/HDF_Group/HDF5/1.10.2\n"
	"\n"
	"Compiling Options:\n"
	"------------------\n"
	"                     Build Mode: \n"
	"              Debugging Symbols: \n"
	"                        Asserts: \n"
	"                      Profiling: \n"
	"             Optimization Level: \n"
	"\n"
	"Linking Options:\n"
	"----------------\n"
	"                      Libraries: \n"
	"  Statically Linked Executables: ON\n"
	"                        LDFLAGS: /machine:x64\n"
	"                     H5_LDFLAGS: \n"
	"                     AM_LDFLAGS: \n"
	"                Extra libraries: \n"
	"                       Archiver: \n"
	"                         Ranlib: \n"
	"\n"
	"Languages:\n"
	"----------\n"
	"                              C: yes\n"
	"                     C Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1\n"
	"                       CPPFLAGS: \n"
	"                    H5_CPPFLAGS: \n"
	"                    AM_CPPFLAGS: \n"
	"                         CFLAGS: /DWIN32 /D_WINDOWS /W3\n"
	"                      H5_CFLAGS: \n"
	"                      AM_CFLAGS: \n"
	"               Shared C Library: NO\n"
	"               Static C Library: YES\n"
	"\n"
	"                        Fortran: OFF\n"
	"               Fortran Compiler:  \n"
	"                  Fortran Flags: \n"
	"               H5 Fortran Flags: \n"
	"               AM Fortran Flags: \n"
	"         Shared Fortran Library: NO\n"
	"         Static Fortran Library: YES\n"
	"\n"
	"                            C++: ON\n"
	"                   C++ Compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe 19.0.24215.1\n"
	"                      C++ Flags: /DWIN32 /D_WINDOWS /W3 /GR /EHsc\n"
	"                   H5 C++ Flags: \n"
	"                   AM C++ Flags: \n"
	"             Shared C++ Library: NO\n"
	"             Static C++ Library: YES\n"
	"\n"
	"                            JAVA: OFF\n"
	"                   JAVA Compiler:  \n"
	"\n"
	"Features:\n"
	"---------\n"
	"                  Parallel HDF5: OFF\n"
	"             High-level library: ON\n"
	"                   Threadsafety: OFF\n"
	"            Default API mapping: v110\n"
	" With deprecated public symbols: ON\n"
	"         I/O filters (external): \n"
	"                            MPE: \n"
	"                     Direct VFD: \n"
	"                        dmalloc: \n"
	" Packages w/ extra debug output: \n"
	"                    API Tracing: OFF\n"
	"           Using memory checker: OFF\n"
	"Memory allocation sanity checks: OFF\n"
	"            Metadata trace file: \n"
	"         Function Stack Tracing: OFF\n"
	"      Strict File Format Checks: OFF\n"
	"   Optimization Instrumentation: \n"
;

#endif

// this version created by the MacOS installation system
#ifdef __APPLE__

/* Generated automatically by H5make_libsettings -- do not edit */



/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * Copyright by the Board of Trustees of the University of Illinois.         *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://support.hdfgroup.org/ftp/HDF5/releases.  *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 *
 * Created:		Apr 22, 2018
 *			wis <wis@wis-Mac-Pro.local>
 *
 * Purpose:		This machine-generated source code contains
 *			information about the library build configuration
 *
 * Modifications:
 *
 *	DO NOT MAKE MODIFICATIONS TO THIS FILE!
 *	It was generated by code in `H5make_libsettings.c'.
 *
 *-------------------------------------------------------------------------
 */

char H5libhdf5_settings[]=
    "	    SUMMARY OF THE HDF5 CONFIGURATION\n"
    "	    =================================\n"
    "\n"
    "General Information:\n"
    "-------------------\n"
    "                   HDF5 Version: 1.10.2\n"
    "                  Configured on: Sun Apr 22 08:33:43 BST 2018\n"
    "                  Configured by: wis@wis-Mac-Pro.local\n"
    "                    Host system: x86_64-apple-darwin17.5.0\n"
    "              Uname information: Darwin wis-Mac-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64\n"
    "                       Byte sex: little-endian\n"
    "             Installation point: /Users/wis/Unix/src/hdf5-1.10.2/hdf5\n"
    "\n"
    "Compiling Options:\n"
    "------------------\n"
    "                     Build Mode: production\n"
    "              Debugging Symbols: no\n"
    "                        Asserts: no\n"
    "                      Profiling: no\n"
    "             Optimization Level: high\n"
    "\n"
    "Linking Options:\n"
    "----------------\n"
    "                      Libraries: static\n"
    "  Statically Linked Executables: \n"
    "                        LDFLAGS: \n"
    "                     H5_LDFLAGS: \n"
    "                     AM_LDFLAGS: \n"
    "                Extra libraries: -lz -ldl -lm \n"
    "                       Archiver: ar\n"
    "                       AR_FLAGS: cr\n"
    "                         Ranlib: ranlib\n"
    "\n"
    "Languages:\n"
    "----------\n"
    "                              C: yes\n"
    "                     C Compiler: /usr/bin/clang ( Apple LLVM version 9.1.0 )\n"
    "                       CPPFLAGS: \n"
    "                    H5_CPPFLAGS:   -DNDEBUG -UH5_DEBUG_API\n"
    "                    AM_CPPFLAGS: \n"
    "                        C Flags: \n"
    "                     H5 C Flags:  -O3   \n"
    "                     AM C Flags: \n"
    "               Shared C Library: no\n"
    "               Static C Library: yes\n"
    "\n"
    "\n"
    "                        Fortran: no\n"
    "\n"
    "                            C++: no\n"
    "\n"
    "                           Java: no\n"
    "\n"
    "\n"
    "Features:\n"
    "---------\n"
    "                  Parallel HDF5: no\n"
    "             High-level library: yes\n"
    "                   Threadsafety: no\n"
    "            Default API mapping: v110\n"
    " With deprecated public symbols: yes\n"
    "         I/O filters (external): deflate(zlib)\n"
    "                            MPE: no\n"
    "                     Direct VFD: no\n"
    "                        dmalloc: no\n"
    " Packages w/ extra debug output: none\n"
    "                    API tracing: no\n"
    "           Using memory checker: no\n"
    "Memory allocation sanity checks: no\n"
    "            Metadata trace file: no\n"
    "         Function stack tracing: no\n"
    "      Strict file format checks: no\n"
    "   Optimization instrumentation: no\n"
;

#endif

